In [1]:
# Core data science libraries
%pip install pandas numpy openpyxl matplotlib seaborn scipy statsmodels

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.6-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy in c:\users\user\appdata\roaming\python\python313\site-packages (2.3.2)
Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting matplotlib
  Downloading matplotlib-3.11.2-cp313-cp313-win_amd64.whl.metadata (80 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting scipy
  Downloading scipy-1.18.1-cp313-cp313-win_amd64.whl.metadata (61 kB)
Collecting statsmodels
  Downloading statsmodels-0.15.0-cp313-cp313-win_amd64.whl.metadata (9.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.4.0-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.66.1-cp313-cp313-win_amd64.whl.metadata (132 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.1-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib) (25.0)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-12.3.0-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.3-py3-none-any.whl.metadata (5.9 kB)
Collecting patsy>=0.5.6 (from statsmodels)
  Downloading patsy-1.0.3-py2.py3-none-any.whl.metadata (3.7 kB)
Collecting formulaic>=1.1.0 (from statsmodels)
  Downloading formulaic-1.2.2-py3-none-any.whl.metadata (7.0 kB)
Collecting interface-meta>=1.2.0 (from formulaic>=1.1.0->statsmodels)
  Downloading interface_meta-2.0.1-py3-none-any.whl.metadata (6.4 kB)
Collecting narwhals>=1.17 (from formulaic>=1.1.0->statsmodels)
  Downloading narwhals-2.26.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from formulaic>=1.1.0->statsmodels) (4.15.0)
Requirement already satisfied: wrapt>=1.17.0rc1 in c:\users\user\appdata\roaming\python\python313\site-packages (from formulaic>=1.1.0->statsmodels) (1.17.3)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp313-cp313-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB 11.8 MB/s eta 0:00:01
   ----------------- ---------------------- 4.2/9.6 MB 11.6 MB/s eta 0:00:01
   --------------------- ------------------ 5.2/9.6 MB 8.9 MB/s eta 0:00:01
   ---------------------------- ----------- 6.8/9.6 MB 8.8 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.6 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 7.8 MB/s  0:00:01
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading matplotlib-3.11.2-cp313-cp313-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/9.3 MB 14.8 MB/s eta 0:00:01
   ----------- ---------------------------- 2.6/9.3 MB 9.3 MB/s eta 0:00:01
   ----------------- ---------------------- 4.2/9.3 MB 7.8 MB/s eta 0:00:01
   ------------------------ --------------- 5.8/9.3 MB 7.8 MB/s eta 0:00:01
   -------------------------------- ------- 7.6/9.3 MB 7.8 MB/s eta 0:00:01
   ---------------------------------------  9.2/9.3 MB 7.8 MB/s eta 0:00:01
   ---------------------------------------- 9.3/9.3 MB 7.6 MB/s  0:00:01
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading scipy-1.18.1-cp313-cp313-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   - -------------------------------------- 1.6/36.6 MB 8.1 MB/s eta 0:00:05
   --- ------------------------------------ 3.1/36.6 MB 7.8 MB/s eta 0:00:05
   ----- ---------------------------------- 5.0/36.6 MB 7.9 MB/s eta 0:00:05
   ------- -------------------------------- 6.8/36.6 MB 8.0 MB/s eta 0:00:04
   --------- ------------------------------ 8.4/36.6 MB 8.0 MB/s eta 0:00:04
   ----------- ---------------------------- 10.2/36.6 MB 8.0 MB/s eta 0:00:04
   ------------- -------------------------- 12.1/36.6 MB 8.1 MB/s eta 0:00:04
   -------------- ------------------------- 13.6/36.6 MB 8.1 MB/s eta 0:00:03
   ---------------- ----------------------- 15.5/36.6 MB 8.1 MB/s eta 0:00:03
   ------------------ --------------------- 16.8/36.6 MB 7.9 MB/s eta 0:00:03
   ------------------- -------------------- 18.1/36.6 MB 7.8 MB/s eta 0:00:03
   --------------------- ------------------ 19.7/36.6 MB 7.7 MB/s eta 0:00:03
   ---------------------- ----------------- 21.0/36.6 MB 7.6 MB/s eta 0:00:03
   ------------------------ --------------- 22.5/36.6 MB 7.6 MB/s eta 0:00:02
   -------------------------- ------------- 23.9/36.6 MB 7.5 MB/s eta 0:00:02
   --------------------------- ------------ 25.4/36.6 MB 7.5 MB/s eta 0:00:02
   ----------------------------- ---------- 27.0/36.6 MB 7.5 MB/s eta 0:00:02
   ------------------------------- -------- 28.8/36.6 MB 7.5 MB/s eta 0:00:02
   --------------------------------- ------ 30.4/36.6 MB 7.5 MB/s eta 0:00:01
   ---------------------------------- ----- 32.0/36.6 MB 7.5 MB/s eta 0:00:01
   ------------------------------------ --- 33.8/36.6 MB 7.5 MB/s eta 0:00:01
   -------------------------------------- - 35.4/36.6 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.6 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------- 36.6/36.6 MB 7.3 MB/s  0:00:04
Downloading statsmodels-0.15.0-cp313-cp313-win_amd64.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.3 MB 6.4 MB/s eta 0:00:02
   -------- ------------------------------- 2.4/11.3 MB 6.0 MB/s eta 0:00:02
   ------------ --------------------------- 3.7/11.3 MB 6.0 MB/s eta 0:00:02
   ----------------- ---------------------- 5.0/11.3 MB 6.1 MB/s eta 0:00:02
   ---------------------- ----------------- 6.3/11.3 MB 6.0 MB/s eta 0:00:01
   ------------------------- -------------- 7.3/11.3 MB 6.0 MB/s eta 0:00:01
   ------------------------------- -------- 8.9/11.3 MB 6.0 MB/s eta 0:00:01
   ------------------------------------ --- 10.2/11.3 MB 6.1 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 6.0 MB/s  0:00:01
Downloading contourpy-1.4.0-cp313-cp313-win_amd64.whl (234 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.66.1-cp313-cp313-win_amd64.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   --------------------- ------------------ 1.3/2.5 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------- 2.5/2.5 MB 6.5 MB/s  0:00:00
Downloading formulaic-1.2.2-py3-none-any.whl (118 kB)
Downloading interface_meta-2.0.1-py3-none-any.whl (15 kB)
Downloading kiwisolver-1.5.1-cp313-cp313-win_amd64.whl (70 kB)
Downloading narwhals-2.26.0-py3-none-any.whl (474 kB)
Downloading patsy-1.0.3-py2.py3-none-any.whl (233 kB)
Downloading pillow-12.3.0-cp313-cp313-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   -------- ------------------------------- 1.6/7.2 MB 6.7 MB/s eta 0:00:01
   --------------- ------------------------ 2.9/7.2 MB 7.0 MB/s eta 0:00:01
   ------------------------ --------------- 4.5/7.2 MB 7.1 MB/s eta 0:00:01
   --------------------------------- ------ 6.0/7.2 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 7.0 MB/s  0:00:01
Downloading pyparsing-3.3.3-py3-none-any.whl (126 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Downloading tzdata-2026.4-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, scipy, pyparsing, pillow, patsy, narwhals, kiwisolver, interface-meta, fonttools, et-xmlfile, cycler, contourpy, pandas, openpyxl, matplotlib, seaborn, formulaic, statsmodels

   ----------------------------------------  0/18 [tzdata]
   ----------------------------------------  0/18 [tzdata]
   ----------------------------------------  0/18 [tzdata]
   ----------------------------------------  0/18 [tzdata]
   ----------------------------------------  0/18 [tzdata]
   ----------------------------------------  0/18 [tzdata]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]
   -- -------------------------------------  1/18 [scipy]

WARNING: Cache entry deserialization failed, entry ignored

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# ================================
# IMPORT REQUIRED LIBRARIES
# ================================

import os
import warnings

import numpy as np
import pandas as pd
import openpyxl

# Ignore unnecessary warning messages during exploration
warnings.filterwarnings("ignore")

# Display more columns/rows when inspecting DataFrames
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

# Display floating-point numbers in a cleaner format
pd.set_option("display.float_format", lambda x: f"{x:,.4f}")

In [4]:
# ================================
# PROJECT PATHS
# ================================

# Path to the original Excel dataset
DATA_PATH = "E:\Projects\Australian Stock Market Data Science Project\data\Aus 1st Half 2025.xlsx"

# Check whether the file exists
if os.path.exists(DATA_PATH):
    print("Dataset found successfully.")
    print("Path:", DATA_PATH)
else:
    print("Dataset not found.")
    print("Please check the DATA_PATH.")

Dataset found successfully.
Path: E:\Projects\Australian Stock Market Data Science Project\data\Aus 1st Half 2025.xlsx

In [5]:
# ================================
# LOAD EXCEL WORKBOOK
# ================================

# Load workbook while preserving formulas
workbook_formulas = openpyxl.load_workbook(
    DATA_PATH,
    data_only=False
)

# Load workbook using the cached/calculated values
workbook_values = openpyxl.load_workbook(
    DATA_PATH,
    data_only=True
)

print("Workbook loaded successfully.")

Workbook loaded successfully.

In [6]:
# ================================
# INSPECT WORKSHEETS
# ================================

sheet_names = workbook_formulas.sheetnames

print("Number of worksheets:", len(sheet_names))
print("\nWorksheet names:")

for sheet in sheet_names:
    print("-", sheet)

Number of worksheets: 1

Worksheet names:
- Sheet1

In [7]:
# ================================
# SELECT MAIN WORKSHEET
# ================================

SHEET_NAME = sheet_names[0]

ws_formula = workbook_formulas[SHEET_NAME]
ws_values = workbook_values[SHEET_NAME]

print("Selected worksheet:", SHEET_NAME)

Selected worksheet: Sheet1

In [8]:
# ================================
# WORKSHEET DIMENSIONS
# ================================

print("Maximum rows:", ws_formula.max_row)
print("Maximum columns:", ws_formula.max_column)

Maximum rows: 55
Maximum columns: 16

In [9]:
# ================================
# EXTRACT COLUMN NAMES
# ================================

columns = [
    ws_formula.cell(row=1, column=col).value
    for col in range(1, ws_formula.max_column + 1)
]

print("Total columns:", len(columns))

for index, column in enumerate(columns, start=1):
    print(f"{index:02d}. {column}")

Total columns: 16
01. TY
02. Company name
03. TOTAL SHARES
04. MARKET CAPITAL(ml)
05. Total Shareholders Equity(ml)
06. 2H2024(JUL-DEC)
07. 1H2025(JAN-JUNE)
08. EPS IN LAST 12 MONTHS
09. EPS AP 24/25
10. P/E BASED ON LAST ANNUAL REPORT
11. AVERAGE P/E FOR LAST 10 YEARS
12. P/E BASED ON LAST 12 MONTHS
13. PRICE
14. book value per share $
15. 52 Weeks Low - High
16. BUY PRICE

In [10]:
# ================================
# LOAD DATASET INTO PANDAS
# ================================

df = pd.read_excel(
    DATA_PATH,
    sheet_name=SHEET_NAME
)

print("Dataset loaded successfully.")
print("Shape:", df.shape)

Dataset loaded successfully.
Shape: (54, 16)

In [11]:
# ================================
# FIRST 5 ROWS
# ================================

df.head()

,TY,Company name,TOTAL SHARES,MARKET CAPITAL(ml),Total Shareholders Equity(ml),2H2024(JUL-DEC),1H2025(JAN-JUNE),EPS IN LAST 12 MONTHS,EPS AP 24/25,P/E BASED ON LAST ANNUAL REPORT,AVERAGE P/E FOR LAST 10 YEARS,P/E BASED ON LAST 12 MONTHS,PRICE,book value per share $,52 Weeks Low - High,BUY PRICE
0,VEA,Viva Energy Group Ltd,1625651926,"3,511.4082",NaN,-0.3000,12.3000,12.0000,4.8000,450.0000,NaN,18.0000,2.1600,1.0270,1.41 - 2.83,NaN
1,DDR,Dicker Data Ltd,180817855,"1,871.4648",NaN,23.9700,21.7900,45.7600,43.6200,237.2765,NaN,22.6180,10.3500,1.3890,7.58 - 10.94,NaN
2,FMG,Fortescue Metals Group Ltd,3078964918,"68,075.9143",NaN,50.5000,39.5500,90.0500,109.7000,201.5497,NaN,24.5530,22.1100,9.8740,13.18 - 22.11,NaN
3,RIO,RIO Tinto Ltd,371216214,"51,402.3092",NaN,315.2000,296.0000,611.2000,669.5000,206.8260,NaN,22.6554,138.4700,54.4740,100.75 - 140.58,NaN
4,APE,Eagers Automotive Ltd,282364338,"7,578.6588",NaN,34.8000,46.4000,81.2000,80.2000,334.6633,NaN,33.0542,26.8400,4.6360,10.90 - 35.64,NaN

In [12]:
# ================================
# LAST 5 ROWS
# ================================

df.tail()

,TY,Company name,TOTAL SHARES,MARKET CAPITAL(ml),Total Shareholders Equity(ml),2H2024(JUL-DEC),1H2025(JAN-JUNE),EPS IN LAST 12 MONTHS,EPS AP 24/25,P/E BASED ON LAST ANNUAL REPORT,AVERAGE P/E FOR LAST 10 YEARS,P/E BASED ON LAST 12 MONTHS,PRICE,book value per share $,52 Weeks Low - High,BUY PRICE
49,SIG,Sigma Healthcare Ltd,11543702836,"33,245.8642",NaN,0.9000,4.2000,5.1000,5.1000,564.7059,NaN,56.4706,2.8800,0.4060,2.57 - 3.32,NaN
50,REH,Reece Ltd,617886428,"7,618.5397",NaN,28.0000,21.0000,49.0000,49.0000,251.6327,NaN,25.1633,12.3300,6.5470,10.14 - 24.60,NaN
51,STP,Step One Clothing Ltd,185340291,59.3089,NaN,4.4100,2.4200,6.8300,6.8300,46.8521,NaN,4.6852,0.3200,0.2850,0.260 - 1.450,NaN
52,ALD,Ampol Ltd,238302099,"7,737.6692",NaN,-47.3000,10.6000,-36.7000,51.4000,631.7121,NaN,-88.4741,32.4700,12.2440,19.53 - 32.74,NaN
53,WPR,Waypoint REIT,652934452,"1,710.6883",NaN,5.6800,20.4900,26.1700,19.5700,133.8784,NaN,10.0115,2.6200,2.9150,2.31 - 2.82,NaN

In [13]:
# ================================
# DATASET STRUCTURE
# ================================

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   TY                               54 non-null     str
 1   Company name                     54 non-null     str
 2   TOTAL SHARES                     54 non-null     int64
 3   MARKET CAPITAL(ml)               54 non-null     float64
 4   Total Shareholders Equity(ml)    0 non-null      float64
 5   2H2024(JUL-DEC)                  54 non-null     float64
 6   1H2025(JAN-JUNE)                 54 non-null     float64
 7   EPS IN LAST 12 MONTHS            54 non-null     float64
 8   EPS AP 24/25                     54 non-null     float64
 9   P/E BASED ON LAST ANNUAL REPORT  52 non-null     float64
 10  AVERAGE P/E FOR LAST 10 YEARS    0 non-null      float64
 11  P/E BASED ON LAST 12 MONTHS      54 non-null     float64
 12  PRICE                            54 non-null     float64
 13  book value per share $           54 non-null     float64
 14  52 Weeks Low - High              54 non-null     str
 15  BUY PRICE                        0 non-null      float64
dtypes: float64(12), int64(1), str(3)
memory usage: 6.9 KB

In [14]:
# ================================
# MISSING VALUE ANALYSIS
# ================================

missing_summary = pd.DataFrame({
    "Missing Count": df.isna().sum(),
    "Missing Percentage": df.isna().mean() * 100
})

# Sort columns from most missing to least missing
missing_summary = missing_summary.sort_values(
    "Missing Count",
    ascending=False
)

missing_summary

                                 Missing Count  Missing Percentage
Total Shareholders Equity(ml)               54            100.0000
AVERAGE P/E FOR LAST 10 YEARS               54            100.0000
BUY PRICE                                   54            100.0000
P/E BASED ON LAST ANNUAL REPORT              2              3.7037
MARKET CAPITAL(ml)                           0              0.0000
TY                                           0              0.0000
TOTAL SHARES                                 0              0.0000
Company name                                 0              0.0000
EPS IN LAST 12 MONTHS                        0              0.0000
1H2025(JAN-JUNE)                             0              0.0000
2H2024(JUL-DEC)                              0              0.0000
EPS AP 24/25                                 0              0.0000
P/E BASED ON LAST 12 MONTHS                  0              0.0000
PRICE                                        0              0.0000
book value per share $                       0              0.0000
52 Weeks Low - High                          0              0.0000

In [15]:
# ================================
# FIND COMPLETELY EMPTY COLUMNS
# ================================

empty_columns = df.columns[df.isna().all()].tolist()

print("Completely empty columns:")
for column in empty_columns:
    print("-", column)

print("\nNumber of completely empty columns:", len(empty_columns))

Completely empty columns:
- Total Shareholders Equity(ml)
- AVERAGE P/E FOR LAST 10 YEARS
- BUY PRICE

Number of completely empty columns: 3

In [16]:
# ================================
# DUPLICATE ROW ANALYSIS
# ================================

duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [17]:
# ================================
# DUPLICATE TICKER ANALYSIS
# ================================

ticker_column = "TY"

duplicate_tickers = df[
    df[ticker_column].duplicated(keep=False)
].sort_values(ticker_column)

duplicate_tickers[
    [ticker_column, "Company name"]
]

     TY         Company name
20  KMD  KMD Brands Limited
44  KMD       KMD Brands Ltd

In [18]:
# ================================
# UNIQUE COMPANY / TICKER COUNTS
# ================================

print("Total rows:", len(df))

print("Unique companies:", df["Company name"].nunique())

print("Unique tickers:", df["TY"].nunique())

print("Duplicate ticker records:",
      len(df) - df["TY"].nunique())

Total rows: 54
Unique companies: 54
Unique tickers: 53
Duplicate ticker records: 1

In [19]:
# ================================
# UNIQUE COMPANY / TICKER COUNTS
# ================================

print("Total rows:", len(df))

print("Unique companies:", df["Company name"].nunique())

print("Unique tickers:", df["TY"].nunique())

print("Duplicate ticker records:",
      len(df) - df["TY"].nunique())

Total rows: 54
Unique companies: 54
Unique tickers: 53
Duplicate ticker records: 1

In [20]:
# ================================
# DESCRIPTIVE STATISTICS
# ================================

numeric_summary = df.describe().T

numeric_summary

,count,mean,std,min,25%,50%,75%,max
TOTAL SHARES,54.0000,"984,683,720.6852","1,725,733,037.8325","68,152,321.0000","186,489,108.7500","334,972,181.0000","1,199,841,181.7500","11,543,702,836.0000"
MARKET CAPITAL(ml),54.0000,"21,124.8517","45,774.9354",7.6707,551.1922,"3,042.9123","12,014.7521","255,604.6406"
Total Shareholders Equity(ml),0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2H2024(JUL-DEC),54.0000,53.8446,98.9270,-47.3000,4.9650,23.1950,55.7500,554.8000
1H2025(JAN-JUNE),54.0000,69.2678,212.2497,-56.3000,4.0725,11.9500,44.9750,"1,473.4400"
EPS IN LAST 12 MONTHS,54.0000,123.1124,269.2455,-36.7000,11.5500,26.6850,95.9750,"1,560.0000"
EPS AP 24/25,54.0000,125.0667,269.9808,0.3900,11.9000,27.4650,97.2500,"1,560.0000"
P/E BASED ON LAST ANNUAL REPORT,52.0000,437.5819,"1,204.5135",9.1958,128.5833,189.5197,313.1506,"8,666.6667"
AVERAGE P/E FOR LAST 10 YEARS,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P/E BASED ON LAST 12 MONTHS,54.0000,38.5956,119.7299,-88.4741,11.5529,18.0883,26.7760,866.6667
PRICE,54.0000,22.1128,39.2854,0.0450,2.1825,7.4100,22.0425,196.3500
book value per share $,54.0000,8.8054,15.4553,0.0600,1.0445,3.3725,9.5705,90.6780
BUY PRICE,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# ================================
# COMPLETE DATASET SUMMARY
# ================================

df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
TY,54,53,KMD,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Company name,54,54,Viva Energy Group Ltd,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TOTAL SHARES,54.0000,NaN,NaN,NaN,"984,683,720.6852","1,725,733,037.8325","68,152,321.0000","186,489,108.7500","334,972,181.0000","1,199,841,181.7500","11,543,702,836.0000"
MARKET CAPITAL(ml),54.0000,NaN,NaN,NaN,"21,124.8517","45,774.9354",7.6707,551.1922,"3,042.9123","12,014.7521","255,604.6406"
Total Shareholders Equity(ml),0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2H2024(JUL-DEC),54.0000,NaN,NaN,NaN,53.8446,98.9270,-47.3000,4.9650,23.1950,55.7500,554.8000
1H2025(JAN-JUNE),54.0000,NaN,NaN,NaN,69.2678,212.2497,-56.3000,4.0725,11.9500,44.9750,"1,473.4400"
EPS IN LAST 12 MONTHS,54.0000,NaN,NaN,NaN,123.1124,269.2455,-36.7000,11.5500,26.6850,95.9750,"1,560.0000"
EPS AP 24/25,54.0000,NaN,NaN,NaN,125.0667,269.9808,0.3900,11.9000,27.4650,97.2500,"1,560.0000"
P/E BASED ON LAST ANNUAL REPORT,52.0000,NaN,NaN,NaN,437.5819,"1,204.5135",9.1958,128.5833,189.5197,313.1506,"8,666.6667"
AVERAGE P/E FOR LAST 10 YEARS,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P/E BASED ON LAST 12 MONTHS,54.0000,NaN,NaN,NaN,38.5956,119.7299,-88.4741,11.5529,18.0883,26.7760,866.6667
PRICE,54.0000,NaN,NaN,NaN,22.1128,39.2854,0.0450,2.1825,7.4100,22.0425,196.3500
book value per share $,54.0000,NaN,NaN,NaN,8.8054,15.4553,0.0600,1.0445,3.3725,9.5705,90.6780
52 Weeks Low - High,54,54,1.41 - 2.83,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BUY PRICE,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
# ================================
# COMPLETE DATASET SUMMARY
# ================================

df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
TY,54,53,KMD,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Company name,54,54,Viva Energy Group Ltd,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TOTAL SHARES,54.0000,NaN,NaN,NaN,"984,683,720.6852","1,725,733,037.8325","68,152,321.0000","186,489,108.7500","334,972,181.0000","1,199,841,181.7500","11,543,702,836.0000"
MARKET CAPITAL(ml),54.0000,NaN,NaN,NaN,"21,124.8517","45,774.9354",7.6707,551.1922,"3,042.9123","12,014.7521","255,604.6406"
Total Shareholders Equity(ml),0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2H2024(JUL-DEC),54.0000,NaN,NaN,NaN,53.8446,98.9270,-47.3000,4.9650,23.1950,55.7500,554.8000
1H2025(JAN-JUNE),54.0000,NaN,NaN,NaN,69.2678,212.2497,-56.3000,4.0725,11.9500,44.9750,"1,473.4400"
EPS IN LAST 12 MONTHS,54.0000,NaN,NaN,NaN,123.1124,269.2455,-36.7000,11.5500,26.6850,95.9750,"1,560.0000"
EPS AP 24/25,54.0000,NaN,NaN,NaN,125.0667,269.9808,0.3900,11.9000,27.4650,97.2500,"1,560.0000"
P/E BASED ON LAST ANNUAL REPORT,52.0000,NaN,NaN,NaN,437.5819,"1,204.5135",9.1958,128.5833,189.5197,313.1506,"8,666.6667"
AVERAGE P/E FOR LAST 10 YEARS,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P/E BASED ON LAST 12 MONTHS,54.0000,NaN,NaN,NaN,38.5956,119.7299,-88.4741,11.5529,18.0883,26.7760,866.6667
PRICE,54.0000,NaN,NaN,NaN,22.1128,39.2854,0.0450,2.1825,7.4100,22.0425,196.3500
book value per share $,54.0000,NaN,NaN,NaN,8.8054,15.4553,0.0600,1.0445,3.3725,9.5705,90.6780
52 Weeks Low - High,54,54,1.41 - 2.83,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BUY PRICE,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# ================================
# IDENTIFY CATEGORICAL COLUMNS
# ================================

categorical_columns = df.select_dtypes(
    exclude=np.number
).columns.tolist()

print("Categorical/text columns:")

for column in categorical_columns:
    print("-", column)

print("\nNumber of categorical columns:", len(categorical_columns))

Categorical/text columns:
- TY
- Company name
- 52 Weeks Low - High

Number of categorical columns: 3

In [24]:
# ================================
# IDENTIFY CATEGORICAL COLUMNS
# ================================

categorical_columns = df.select_dtypes(
    exclude=np.number
).columns.tolist()

print("Categorical/text columns:")

for column in categorical_columns:
    print("-", column)

print("\nNumber of categorical columns:", len(categorical_columns))

Categorical/text columns:
- TY
- Company name
- 52 Weeks Low - High

Number of categorical columns: 3

In [26]:
# ============================================
# CHECK NEGATIVE VALUES
# ============================================

# Identify all numeric columns in the dataset.
# This makes the cell independent of the previous cells.
numeric_columns = df.select_dtypes(include=np.number).columns.tolist()

# Count how many negative values exist in each numeric column.
negative_summary = pd.DataFrame({
    "Negative Count": [
        (df[column] < 0).sum()
        for column in numeric_columns
    ]
}, index=numeric_columns)

# Display the result
negative_summary

                                 Negative Count
TOTAL SHARES                                  0
MARKET CAPITAL(ml)                            0
Total Shareholders Equity(ml)                 0
2H2024(JUL-DEC)                               2
1H2025(JAN-JUNE)                              5
EPS IN LAST 12 MONTHS                         1
EPS AP 24/25                                  0
P/E BASED ON LAST ANNUAL REPORT               0
AVERAGE P/E FOR LAST 10 YEARS                 0
P/E BASED ON LAST 12 MONTHS                   1
PRICE                                         0
book value per share $                        0
BUY PRICE                                     0

In [27]:
# ================================
# CHECK ZERO VALUES
# ================================

zero_summary = pd.DataFrame({
    "Zero Count": [
        (df[column] == 0).sum()
        for column in numeric_columns
    ]
}, index=numeric_columns)

zero_summary

                                 Zero Count
TOTAL SHARES                              0
MARKET CAPITAL(ml)                        0
Total Shareholders Equity(ml)             0
2H2024(JUL-DEC)                           0
1H2025(JAN-JUNE)                          0
EPS IN LAST 12 MONTHS                     0
EPS AP 24/25                              0
P/E BASED ON LAST ANNUAL REPORT           0
AVERAGE P/E FOR LAST 10 YEARS             0
P/E BASED ON LAST 12 MONTHS               0
PRICE                                     0
book value per share $                    0
BUY PRICE                                 0

In [28]:
# ================================
# INSPECT 52-WEEK RANGE VALUES
# ================================

df[
    ["TY", "Company name", "52 Weeks Low - High"]
].to_string(index=False)

'   TY                                Company name 52 Weeks Low - High\n  VEA                       Viva Energy Group Ltd         1.41 - 2.83\n  DDR                             Dicker Data Ltd        7.58 - 10.94\n  FMG                  Fortescue Metals Group Ltd       13.18 - 22.11\n  RIO                               RIO Tinto Ltd     100.75 - 140.58\n  APE                       Eagers Automotive Ltd       10.90 - 35.64\n  AFG               Australian Finance Group Ltd\xa0        1.425 - 2.92\n  ASH                       Ashley Services Group       0.128 - 0.245\n  ASG                        Autosports Group Ltd        1.605 - 4.70\n  SGM                                    Sims Ltd       11.63 - 18.11\n  ACL                Australian Clinical Labs Ltd         2.38 - 3.83\n  ORA                               Orora Limited        1.655 - 2.50\n  HLI                             Helia Group Ltd         3.43 - 6.19\n  LAU                   Lindsay Australia Limited       0.580 - 0.910\n  GAP                            Gale Pacific Ltd       0.086 - 0.140\n  ELD                                 Elders Ltd\xa0         5.73 - 7.91\n  GNC                              Graincorp Ltd\xa0         6.34 - 9.13\nSGLLV                             Ricegrowers Ltd        9.15 - 18.63\n  PWR    Peter Warren Automotive Holdings Limited        1.210 - 2.05\n  PLS                        Pilbara Minerals Ltd         1.07 - 4.26\n  KGN                               Kogan.com Ltd         2.88 - 6.37\n  KMD                         KMD\xa0Brands Limited\xa0       0.205 - 0.400\n  AX1                            Accent Group Ltd        0.915 - 2.46\n  CBA              Commonwealth Bank\xa0of\xa0Australia        140.21 - 192\n  WBC                 Westpac Banking Corporation          28.44 - 41\n  NAB                 National Australia Bank Ltd       31.13 - 45.25\n  MQG                     Macquarie Group\xa0Limited       160  - 242.90\n  QBE                 QBE\xa0Insurance Group Limited       18.34 - 24.20\n  SUN                           Suncorp Group Ltd       16.63 - 22.14\n  IAG               Insurance Australia Group Ltd         7.10 - 9.21\n  BEN               Bendigo and Adelaide Bank Ltd        9.50 - 13.73\n  ANZ Australia and New Zealand Banking Group Ltd       26.22 - 38.93\n  BOQ                      Bank of Queensland Ltd         6.20 - 8.16\n  SVR                                  Solvar Ltd       1.225 - 1.830\n  COL                         Coles Group Limited       18.33 - 24.28\n  A2M                         a2 Milk Company Ltd         5.43 - 9.78\n  BGA                            Bega Cheese Ltd\xa0         4.85 - 6.30\n  PTL                                  Pental Ltd       0.041 - 0.097\n  WOW                        Woolworths Group Ltd      25.52 0- 33.76\n  BRG                          Breville Group Ltd          24.33 - 39\n  SUL                      Super Retail Group Ltd       12.06 - 20.20\n  ADH                                  Adairs Ltd        1.745 - 2.99\n  MTO                     Motorcycle Holdings Ltd           1.635 - 4\n  NTD                   National Tyre & Wheel Ltd       0.160 - 0.400\n  JBH                                JB Hi-Fi Ltd         83.32 - 121\n  KMD                              KMD Brands Ltd        0.205 - 0.40\n  CFK                           Collins Foods Ltd        7.04 - 12.73\n  WES                              Wesfarmers Ltd       67.70 - 95.18\n  HVN                  Harvey Norman Holdings Ltd         4.53 - 7.70\n  ANN                                  Ansell Ltd       28.19 - 37.85\n  SIG                        Sigma Healthcare Ltd         2.57 - 3.32\n  REH                                   Reece Ltd      10.14  - 24.60\n  STP                       Step One Clothing Ltd       0.260 - 1.450\n  ALD                                   Ampol Ltd       19.53 - 32.74\n  WPR                               Waypoint REIT         2.31 - 2.82'

In [29]:
# ================================
# VALIDATE 52-WEEK RANGE FORMAT
# ================================

range_validation = []

for index, value in df["52 Weeks Low - High"].items():

    # Convert the value to text
    text_value = str(value).strip()

    # Split using the hyphen
    parts = text_value.split("-")

    # A valid range should contain exactly two parts
    is_valid = len(parts) == 2

    range_validation.append({
        "Row": index,
        "Ticker": df.loc[index, "TY"],
        "Raw Value": value,
        "Number of Parts": len(parts),
        "Format Valid": is_valid
    })

range_validation_df = pd.DataFrame(range_validation)

range_validation_df[
    ~range_validation_df["Format Valid"]
]

Empty DataFrame
Columns: [Row, Ticker, Raw Value, Number of Parts, Format Valid]
Index: []

In [30]:
# ================================
# INSPECT EXCEL FORMULAS
# ================================

formula_records = []

for row in range(2, ws_formula.max_row + 1):

    ticker = ws_formula.cell(row=row, column=1).value

    for column in range(1, ws_formula.max_column + 1):

        cell = ws_formula.cell(row=row, column=column)

        # Check whether the Excel cell contains a formula
        if isinstance(cell.value, str) and cell.value.startswith("="):

            formula_records.append({
                "Excel Row": row,
                "Ticker": ticker,
                "Column": ws_formula.cell(
                    row=1,
                    column=column
                ).value,
                "Formula": cell.value,
                "Calculated Value": ws_values.cell(
                    row=row,
                    column=column
                ).value
            })

formula_df = pd.DataFrame(formula_records)

formula_df.head(20)

,Excel Row,Ticker,Column,Formula,Calculated Value
0,2,VEA,MARKET CAPITAL(ml),=(C2*M2)/1000000,"3,511.4082"
1,2,VEA,EPS IN LAST 12 MONTHS,=F2+G2,12
2,2,VEA,P/E BASED ON LAST ANNUAL REPORT,=(M2/I2)*1000,450.0000
3,2,VEA,P/E BASED ON LAST 12 MONTHS,=(M2/H2)*100,18.0000
4,3,DDR,MARKET CAPITAL(ml),=(C3*M3)/1000000,"1,871.4648"
5,3,DDR,EPS IN LAST 12 MONTHS,=F3+G3,45.7600
6,3,DDR,P/E BASED ON LAST ANNUAL REPORT,=(M3/I3)*1000,237.2765
7,3,DDR,P/E BASED ON LAST 12 MONTHS,=(M3/H3)*100,22.6180
8,4,FMG,MARKET CAPITAL(ml),=(C4*M4)/1000000,"68,075.9143"
9,4,FMG,EPS IN LAST 12 MONTHS,=F4+G4,90.0500
10,4,FMG,P/E BASED ON LAST ANNUAL REPORT,=(M4/I4)*1000,201.5497
11,4,FMG,P/E BASED ON LAST 12 MONTHS,=(M4/H4)*100,24.5530
12,5,RIO,MARKET CAPITAL(ml),=(C5*M5)/1000000,"51,402.3092"
13,5,RIO,EPS IN LAST 12 MONTHS,=F5+G5,611.2000
14,5,RIO,P/E BASED ON LAST ANNUAL REPORT,=(M5/I5)*1000,206.8260
15,5,RIO,P/E BASED ON LAST 12 MONTHS,=(M5/H5)*100,22.6554
16,6,APE,MARKET CAPITAL(ml),=(C6*M6)/1000000,"7,578.6588"
17,6,APE,EPS IN LAST 12 MONTHS,=F6+G6,81.2000
18,6,APE,P/E BASED ON LAST ANNUAL REPORT,=(M6/I6)*1000,334.6633
19,6,APE,P/E BASED ON LAST 12 MONTHS,=(M6/H6)*100,33.0542

In [31]:
# ================================
# FORMULA COUNT
# ================================

print("Total formula cells:", len(formula_df))

print(
    "Columns containing formulas:",
    formula_df["Column"].nunique()
)

formula_df["Column"].value_counts()

Total formula cells: 263
Columns containing formulas: 6

Column
MARKET CAPITAL(ml)                 54
EPS IN LAST 12 MONTHS              54
P/E BASED ON LAST ANNUAL REPORT    54
P/E BASED ON LAST 12 MONTHS        54
1H2025(JAN-JUNE)                   43
2H2024(JUL-DEC)                     4
Name: count, dtype: int64

In [32]:
# ================================
# DETECT EXCEL FORMULA ERRORS
# ================================

excel_error_patterns = [
    "#REF!",
    "#DIV/0!",
    "#VALUE!",
    "#NAME?",
    "#N/A",
    "#NUM!",
    "#NULL!"
]

formula_errors = formula_df[
    formula_df["Formula"].astype(str).apply(
        lambda x: any(error in x for error in excel_error_patterns)
    )
]

formula_errors

,Excel Row,Ticker,Column,Formula,Calculated Value
58,14,LAU,P/E BASED ON LAST ANNUAL REPORT,=(M14/#REF!)*1000,#REF!
176,38,PTL,P/E BASED ON LAST ANNUAL REPORT,=(M38/#REF!)*1000,#REF!

In [33]:
# ================================
# CHECK CALCULATED VALUES
# ================================

calculated_value_errors = formula_df[
    formula_df["Calculated Value"].astype(str).isin(
        excel_error_patterns
    )
]

calculated_value_errors

,Excel Row,Ticker,Column,Formula,Calculated Value
58,14,LAU,P/E BASED ON LAST ANNUAL REPORT,=(M14/#REF!)*1000,#REF!
176,38,PTL,P/E BASED ON LAST ANNUAL REPORT,=(M38/#REF!)*1000,#REF!

In [34]:
# ================================
# FORMULA DISTRIBUTION BY COLUMN
# ================================

formula_by_column = (
    formula_df
    .groupby("Column")
    .size()
    .sort_values(ascending=False)
)

formula_by_column

Column
MARKET CAPITAL(ml)                 54
EPS IN LAST 12 MONTHS              54
P/E BASED ON LAST 12 MONTHS        54
P/E BASED ON LAST ANNUAL REPORT    54
1H2025(JAN-JUNE)                   43
2H2024(JUL-DEC)                     4
dtype: int64

In [35]:
# ================================
# INITIAL RAW / DERIVED CLASSIFICATION
# ================================

derived_columns = [
    "MARKET CAPITAL(ml)",
    "EPS IN LAST 12 MONTHS",
    "P/E BASED ON LAST ANNUAL REPORT",
    "P/E BASED ON LAST 12 MONTHS"
]

raw_columns = [
    column
    for column in df.columns
    if column not in derived_columns
]

feature_classification = pd.DataFrame({
    "Column": df.columns,
    "Classification": [
        "Derived / calculated"
        if column in derived_columns
        else "Raw / supplied"
        for column in df.columns
    ]
})

feature_classification

                             Column        Classification
0                                TY        Raw / supplied
1                      Company name        Raw / supplied
2                      TOTAL SHARES        Raw / supplied
3                MARKET CAPITAL(ml)  Derived / calculated
4     Total Shareholders Equity(ml)        Raw / supplied
5                   2H2024(JUL-DEC)        Raw / supplied
6                  1H2025(JAN-JUNE)        Raw / supplied
7             EPS IN LAST 12 MONTHS  Derived / calculated
8                      EPS AP 24/25        Raw / supplied
9   P/E BASED ON LAST ANNUAL REPORT  Derived / calculated
10    AVERAGE P/E FOR LAST 10 YEARS        Raw / supplied
11      P/E BASED ON LAST 12 MONTHS  Derived / calculated
12                            PRICE        Raw / supplied
13           book value per share $        Raw / supplied
14              52 Weeks Low - High        Raw / supplied
15                        BUY PRICE        Raw / supplied

In [36]:
# ================================
# VALIDATE MARKET CAPITALIZATION
# ================================

df["Calculated Market Cap"] = (
    df["TOTAL SHARES"] *
    df["PRICE"] /
    1_000_000
)

df["Market Cap Difference"] = (
    df["MARKET CAPITAL(ml)"] -
    df["Calculated Market Cap"]
)

market_cap_validation = df[
    [
        "TY",
        "MARKET CAPITAL(ml)",
        "Calculated Market Cap",
        "Market Cap Difference"
    ]
]

market_cap_validation.head(10)

    TY  MARKET CAPITAL(ml)  Calculated Market Cap  Market Cap Difference
0  VEA          3,511.4082             3,511.4082                 0.0000
1  DDR          1,871.4648             1,871.4648                 0.0000
2  FMG         68,075.9143            68,075.9143                 0.0000
3  RIO         51,402.3092            51,402.3092                 0.0000
4  APE          7,578.6588             7,578.6588                 0.0000
5  AFG            611.4601               611.4601                 0.0000
6  ASH             30.9548                30.9548                 0.0000
7  ASG            857.3504               857.3504                 0.0000
8  SGM          3,433.7232             3,433.7232                 0.0000
9  ACL            550.5593               550.5593                 0.0000

In [37]:
# ================================
# IDENTIFY MARKET CAP DIFFERENCES
# ================================

market_cap_problems = market_cap_validation[
    market_cap_validation["Market Cap Difference"].abs() > 0.01
]

market_cap_problems

     TY  MARKET CAPITAL(ml)  Calculated Market Cap  Market Cap Difference
37  WOW          3,053.9933            35,902.7452           -32,848.7519
43  JBH          3,031.8313             9,775.5512            -6,743.7199

In [38]:
# ================================
# VALIDATE LTM EPS
# ================================

df["Calculated LTM EPS"] = (
    df["2H2024(JUL-DEC)"] +
    df["1H2025(JAN-JUNE)"]
)

df["EPS Difference"] = (
    df["EPS IN LAST 12 MONTHS"] -
    df["Calculated LTM EPS"]
)

eps_validation = df[
    [
        "TY",
        "EPS IN LAST 12 MONTHS",
        "Calculated LTM EPS",
        "EPS Difference"
    ]
]

eps_validation

       TY  EPS IN LAST 12 MONTHS  Calculated LTM EPS  EPS Difference
0     VEA                12.0000             12.0000          0.0000
1     DDR                45.7600             45.7600          0.0000
2     FMG                90.0500             90.0500          0.0000
3     RIO               611.2000            611.2000          0.0000
4     APE                81.2000             81.2000          0.0000
5     AFG                15.1000             15.1000          0.0000
6     ASH                 1.5100              1.5100          0.0000
7     ASG                16.2600             16.2600          0.0000
8     SGM                 9.9000              9.9000          0.0000
9     ACL                17.1500             17.1500          0.0000
10    ORA                11.4000             11.4000          0.0000
11    HLI                96.5000             96.5000          0.0000
12    LAU                 5.5000              5.5000          0.0000
13    GAP                 1.8200              1.8200          0.0000
14    ELD                27.2000             27.2000          0.0000
15    GNC                18.2000             18.2000          0.0000
16  SGLLV               102.9000            102.9000          0.0000
17    PWR                 7.0300              7.0300          0.0000
18    PLS                 6.3300              6.3300          0.0000
19    KGN                 0.3900              0.3900          0.0000
20    KMD                13.4000             13.4000          0.0000
21    AX1                10.1200             10.1200          0.0000
22    CBA               613.2000            613.2000          0.0000
23    WBC               206.3000            206.3000          0.0000
24    NAB               221.9000            221.9000          0.0000
25    MQG               991.5000            991.5000          0.0000
26    QBE               129.4000            129.4000          0.0000
27    SUN             1,560.0000          1,560.0000          0.0000
28    IAG                57.4700             57.4700          0.0000
29    BEN                17.2000             17.2000          0.0000
30    ANZ               194.7000            194.7000          0.0000
31    BOQ                53.9000             53.9000          0.0000
32    SVR                15.4800             15.4800          0.0000
33    COL                80.8000             80.8000          0.0000
34    A2M                28.0000             28.0000          0.0000
35    BGA                16.6000             16.6000          0.0000
36    PTL                 2.5000              2.5000          0.0000
37    WOW                78.9000             78.9000          0.0000
38    BRG                94.4000             94.4000          0.0000
39    SUL                98.2000             98.2000          0.0000
40    ADH                14.6000             14.6000          0.0000
41    MTO                24.4000             24.4000          0.0000
42    NTD                27.7300             27.7300          0.0000
43    JBH               423.0000            423.0000          0.0000
44    KMD                13.4000             13.4000          0.0000
45    CFK                 7.5000              7.5000          0.0000
46    WES               258.0000            258.0000          0.0000
47    HVN                41.5700             41.5700          0.0000
48    ANN               126.1000            126.1000          0.0000
49    SIG                 5.1000              5.1000          0.0000
50    REH                49.0000             49.0000          0.0000
51    STP                 6.8300              6.8300          0.0000
52    ALD               -36.7000            -36.7000          0.0000
53    WPR                26.1700             26.1700          0.0000

In [39]:
# ================================
# IDENTIFY EPS DIFFERENCES
# ================================

eps_problems = eps_validation[
    eps_validation["EPS Difference"].abs() > 0.0001
]

eps_problems

Empty DataFrame
Columns: [TY, EPS IN LAST 12 MONTHS, Calculated LTM EPS, EPS Difference]
Index: []

In [40]:
# ================================
# VALIDATE LTM P/E
# ================================

df["Calculated LTM P/E"] = (
    df["PRICE"] /
    df["EPS IN LAST 12 MONTHS"]
) * 100

df["P/E Difference"] = (
    df["P/E BASED ON LAST 12 MONTHS"] -
    df["Calculated LTM P/E"]
)

pe_validation = df[
    [
        "TY",
        "P/E BASED ON LAST 12 MONTHS",
        "Calculated LTM P/E",
        "P/E Difference"
    ]
]

pe_validation.head(10)

    TY  P/E BASED ON LAST 12 MONTHS  Calculated LTM P/E  P/E Difference
0  VEA                      18.0000             18.0000          0.0000
1  DDR                      22.6180             22.6180          0.0000
2  FMG                      24.5530             24.5530          0.0000
3  RIO                      22.6554             22.6554          0.0000
4  APE                      33.0542             33.0542          0.0000
5  AFG                      14.9007             14.9007          0.0000
6  ASH                      14.2384             14.2384          0.0000
7  ASG                      26.0148             26.0148          0.0000
8  SGM                     179.4949            179.4949          0.0000
9  ACL                      16.5598             16.5598          0.0000

In [41]:
# ================================
# VALIDATE LTM P/E
# ================================

df["Calculated LTM P/E"] = (
    df["PRICE"] /
    df["EPS IN LAST 12 MONTHS"]
) * 100

df["P/E Difference"] = (
    df["P/E BASED ON LAST 12 MONTHS"] -
    df["Calculated LTM P/E"]
)

pe_validation = df[
    [
        "TY",
        "P/E BASED ON LAST 12 MONTHS",
        "Calculated LTM P/E",
        "P/E Difference"
    ]
]

pe_validation.head(10)

    TY  P/E BASED ON LAST 12 MONTHS  Calculated LTM P/E  P/E Difference
0  VEA                      18.0000             18.0000          0.0000
1  DDR                      22.6180             22.6180          0.0000
2  FMG                      24.5530             24.5530          0.0000
3  RIO                      22.6554             22.6554          0.0000
4  APE                      33.0542             33.0542          0.0000
5  AFG                      14.9007             14.9007          0.0000
6  ASH                      14.2384             14.2384          0.0000
7  ASG                      26.0148             26.0148          0.0000
8  SGM                     179.4949            179.4949          0.0000
9  ACL                      16.5598             16.5598          0.0000

In [48]:
# ============================================
# IDENTIFY ALL LTM P/E CALCULATION PROBLEMS
# ============================================

# Find companies where the Excel P/E differs
# from our independently calculated P/E.
#
# We use a small tolerance (0.01) because
# tiny floating-point differences are acceptable.

pe_problems = pe_validation[
    pe_validation["P/E Difference"].abs() > 0.01
]

# Display all problematic records
pe_problems

     TY  P/E BASED ON LAST 12 MONTHS  Calculated LTM P/E  P/E Difference
37  WOW                       3.1686             37.2497        -34.0811
43  JBH                       6.5556             21.1371        -14.5816

In [42]:
# ================================
# PRELIMINARY DATA DICTIONARY
# ================================

data_dictionary = pd.DataFrame([
    {
        "Column": "TY",
        "Meaning": "Company ticker / trading symbol",
        "Type": "Categorical",
        "Unit": "Ticker",
        "Role": "Identifier",
        "Raw_or_Derived": "Raw"
    },
    {
        "Column": "Company name",
        "Meaning": "Company name",
        "Type": "Categorical",
        "Unit": "Text",
        "Role": "Identifier",
        "Raw_or_Derived": "Raw"
    },
    {
        "Column": "TOTAL SHARES",
        "Meaning": "Total number of shares",
        "Type": "Numeric",
        "Unit": "Shares",
        "Role": "Feature",
        "Raw_or_Derived": "Raw"
    },
    {
        "Column": "MARKET CAPITAL(ml)",
        "Meaning": "Market capitalization",
        "Type": "Numeric",
        "Unit": "Millions",
        "Role": "Feature",
        "Raw_or_Derived": "Derived"
    },
    {
        "Column": "Total Shareholders Equity(ml)",
        "Meaning": "Shareholders' equity",
        "Type": "Numeric",
        "Unit": "Millions",
        "Role": "Potential Feature",
        "Raw_or_Derived": "Raw / currently empty"
    },
    {
        "Column": "2H2024(JUL-DEC)",
        "Meaning": "Second-half 2024 earnings/EPS input",
        "Type": "Numeric",
        "Unit": "Dataset-defined",
        "Role": "Feature",
        "Raw_or_Derived": "Raw / partly formula-derived"
    },
    {
        "Column": "1H2025(JAN-JUNE)",
        "Meaning": "First-half 2025 earnings/EPS input",
        "Type": "Numeric",
        "Unit": "Dataset-defined",
        "Role": "Feature",
        "Raw_or_Derived": "Raw / partly formula-derived"
    },
    {
        "Column": "EPS IN LAST 12 MONTHS",
        "Meaning": "Earnings per share over the last 12 months",
        "Type": "Numeric",
        "Unit": "Dataset-defined",
        "Role": "Feature",
        "Raw_or_Derived": "Derived"
    },
    {
        "Column": "EPS AP 24/25",
        "Meaning": "Annual-period EPS figure",
        "Type": "Numeric",
        "Unit": "Dataset-defined",
        "Role": "Feature",
        "Raw_or_Derived": "Raw / requires validation"
    },
    {
        "Column": "P/E BASED ON LAST ANNUAL REPORT",
        "Meaning": "P/E calculated using annual-report EPS",
        "Type": "Numeric",
        "Unit": "Ratio",
        "Role": "Feature",
        "Raw_or_Derived": "Derived"
    },
    {
        "Column": "AVERAGE P/E FOR LAST 10 YEARS",
        "Meaning": "Historical average P/E",
        "Type": "Numeric",
        "Unit": "Ratio",
        "Role": "Potential Feature",
        "Raw_or_Derived": "Raw / currently empty"
    },
    {
        "Column": "P/E BASED ON LAST 12 MONTHS",
        "Meaning": "P/E based on LTM EPS",
        "Type": "Numeric",
        "Unit": "Ratio",
        "Role": "Feature",
        "Raw_or_Derived": "Derived"
    },
    {
        "Column": "PRICE",
        "Meaning": "Current/share price in dataset",
        "Type": "Numeric",
        "Unit": "Currency",
        "Role": "Feature",
        "Raw_or_Derived": "Raw"
    },
    {
        "Column": "book value per share $",
        "Meaning": "Book value per share",
        "Type": "Numeric",
        "Unit": "Currency/share",
        "Role": "Feature",
        "Raw_or_Derived": "Raw"
    },
    {
        "Column": "52 Weeks Low - High",
        "Meaning": "52-week low and high price range",
        "Type": "Text / Range",
        "Unit": "Currency",
        "Role": "Feature after parsing",
        "Raw_or_Derived": "Raw"
    },
    {
        "Column": "BUY PRICE",
        "Meaning": "Buy-price field; origin/definition not established",
        "Type": "Numeric",
        "Unit": "Unknown",
        "Role": "Potential Feature",
        "Raw_or_Derived": "Raw / currently empty"
    }
])

data_dictionary

,Column,Meaning,Type,Unit,Role,Raw_or_Derived
0,TY,Company ticker / trading symbol,Categorical,Ticker,Identifier,Raw
1,Company name,Company name,Categorical,Text,Identifier,Raw
2,TOTAL SHARES,Total number of shares,Numeric,Shares,Feature,Raw
3,MARKET CAPITAL(ml),Market capitalization,Numeric,Millions,Feature,Derived
4,Total Shareholders Equity(ml),Shareholders' equity,Numeric,Millions,Potential Feature,Raw / currently empty
5,2H2024(JUL-DEC),Second-half 2024 earnings/EPS input,Numeric,Dataset-defined,Feature,Raw / partly formula-derived
6,1H2025(JAN-JUNE),First-half 2025 earnings/EPS input,Numeric,Dataset-defined,Feature,Raw / partly formula-derived
7,EPS IN LAST 12 MONTHS,Earnings per share over the last 12 months,Numeric,Dataset-defined,Feature,Derived
8,EPS AP 24/25,Annual-period EPS figure,Numeric,Dataset-defined,Feature,Raw / requires validation
9,P/E BASED ON LAST ANNUAL REPORT,P/E calculated using annual-report EPS,Numeric,Ratio,Feature,Derived
10,AVERAGE P/E FOR LAST 10 YEARS,Historical average P/E,Numeric,Ratio,Potential Feature,Raw / currently empty
11,P/E BASED ON LAST 12 MONTHS,P/E based on LTM EPS,Numeric,Ratio,Feature,Derived
12,PRICE,Current/share price in dataset,Numeric,Currency,Feature,Raw
13,book value per share $,Book value per share,Numeric,Currency/share,Feature,Raw
14,52 Weeks Low - High,52-week low and high price range,Text / Range,Currency,Feature after parsing,Raw
15,BUY PRICE,Buy-price field; origin/definition not establi...,Numeric,Unknown,Potential Feature,Raw / currently empty

In [43]:
# ================================
# PHASE 1 DATA QUALITY SUMMARY
# ================================

phase1_summary = {
    "Rows": len(df),
    "Columns": len(df.columns),
    "Unique Companies": df["Company name"].nunique(),
    "Unique Tickers": df["TY"].nunique(),
    "Duplicate Rows": int(df.duplicated().sum()),
    "Duplicate Tickers": int(df["TY"].duplicated().sum()),
    "Completely Empty Columns": len(empty_columns),
    "Formula Cells": len(formula_df),
    "Formula Error Cells": len(calculated_value_errors),
    "Numeric Columns": len(numeric_columns),
    "Text Columns": len(categorical_columns)
}

phase1_summary_df = pd.DataFrame(
    phase1_summary.items(),
    columns=["Metric", "Value"]
)

phase1_summary_df

                      Metric  Value
0                       Rows     54
1                    Columns     22
2           Unique Companies     54
3             Unique Tickers     53
4             Duplicate Rows      0
5          Duplicate Tickers      1
6   Completely Empty Columns      3
7              Formula Cells    263
8        Formula Error Cells      2
9            Numeric Columns     13
10              Text Columns      3

In [44]:
# ================================
# PHASE 1 FINDINGS
# ================================

print("=" * 70)
print("PHASE 1 — DATASET UNDERSTANDING")
print("=" * 70)

print(f"\nDataset size: {df.shape[0]} companies × {df.shape[1]} columns")

print(f"\nUnique companies: {df['Company name'].nunique()}")
print(f"Unique tickers: {df['TY'].nunique()}")

print(f"\nDuplicate rows: {df.duplicated().sum()}")
print(f"Duplicate ticker records: {df['TY'].duplicated().sum()}")

print("\nCompletely empty columns:")
for column in empty_columns:
    print(f"  - {column}")

print(f"\nFormula cells: {len(formula_df)}")
print(f"Formula-error cells: {len(calculated_value_errors)}")

print("\nPhase 1 completed.")

======================================================================
PHASE 1 — DATASET UNDERSTANDING
======================================================================

Dataset size: 54 companies × 22 columns

Unique companies: 54
Unique tickers: 53

Duplicate rows: 0
Duplicate ticker records: 1

Completely empty columns:
  - Total Shareholders Equity(ml)
  - AVERAGE P/E FOR LAST 10 YEARS
  - BUY PRICE

Formula cells: 263
Formula-error cells: 2

Phase 1 completed.

In [46]:
# ============================================
# SAVE PHASE 1 METADATA
# ============================================

# Create the metadata folder if it doesn't already exist
metadata_dir = "../data/metadata"
os.makedirs(metadata_dir, exist_ok=True)


# --------------------------------------------
# 1. Recreate the column profile
# --------------------------------------------

# This ensures dtype_summary exists even if Cell 13
# was not executed earlier.
dtype_summary = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str).values,
    "Non-Null Count": df.notna().sum().values,
    "Missing Count": df.isna().sum().values,
    "Missing %": (df.isna().mean() * 100).round(2).values
})


# --------------------------------------------
# 2. Save the data dictionary
# --------------------------------------------

data_dictionary.to_csv(
    f"{metadata_dir}/data_dictionary_phase1.csv",
    index=False
)


# --------------------------------------------
# 3. Save column profile
# --------------------------------------------

dtype_summary.to_csv(
    f"{metadata_dir}/column_profile_phase1.csv",
    index=False
)


# --------------------------------------------
# 4. Save Excel formula audit
# --------------------------------------------

formula_df.to_csv(
    f"{metadata_dir}/excel_formula_audit_phase1.csv",
    index=False
)


# --------------------------------------------
# 5. Recreate Phase 1 summary
# --------------------------------------------

# Identify completely empty columns again
empty_columns = df.columns[df.isna().all()].tolist()

# Count numeric columns
numeric_columns = df.select_dtypes(
    include=np.number
).columns.tolist()

# Count text/categorical columns
categorical_columns = df.select_dtypes(
    exclude=np.number
).columns.tolist()

# Create the summary information
phase1_summary = {
    "Rows": len(df),
    "Columns": len(df.columns),
    "Unique Companies": df["Company name"].nunique(),
    "Unique Tickers": df["TY"].nunique(),
    "Duplicate Rows": int(df.duplicated().sum()),
    "Duplicate Tickers": int(df["TY"].duplicated().sum()),
    "Completely Empty Columns": len(empty_columns),
    "Formula Cells": len(formula_df),
    "Formula Error Cells": len(calculated_value_errors),
    "Numeric Columns": len(numeric_columns),
    "Text Columns": len(categorical_columns)
}

phase1_summary_df = pd.DataFrame(
    phase1_summary.items(),
    columns=["Metric", "Value"]
)


# --------------------------------------------
# 6. Save Phase 1 summary
# --------------------------------------------

phase1_summary_df.to_csv(
    f"{metadata_dir}/phase1_summary.csv",
    index=False
)


# --------------------------------------------
# 7. Confirm everything was saved
# --------------------------------------------

print("Phase 1 metadata saved successfully.")
print("\nFiles created:")

print("- data_dictionary_phase1.csv")
print("- column_profile_phase1.csv")
print("- excel_formula_audit_phase1.csv")
print("- phase1_summary.csv")

print(f"\nLocation: {metadata_dir}")

Phase 1 metadata saved successfully.

Files created:
- data_dictionary_phase1.csv
- column_profile_phase1.csv
- excel_formula_audit_phase1.csv
- phase1_summary.csv

Location: ../data/metadata

In [47]:
# ================================
# PHASE 1 COMPLETION CHECKLIST
# ================================

checklist = {
    "Workbook inspected": len(sheet_names) > 0,
    "Dataset loaded": df.shape[0] > 0,
    "Columns inspected": len(df.columns) > 0,
    "Missing values analyzed": True,
    "Duplicate rows analyzed": True,
    "Duplicate tickers analyzed": True,
    "Data types analyzed": True,
    "Descriptive statistics generated": True,
    "52-week range inspected": True,
    "Excel formulas inspected": len(formula_df) > 0,
    "Formula errors checked": True,
    "Derived features identified": True,
    "Data dictionary created": len(data_dictionary) == len(df.columns)
}

checklist_df = pd.DataFrame(
    checklist.items(),
    columns=["Phase 1 Task", "Completed"]
)

checklist_df

                        Phase 1 Task  Completed
0                 Workbook inspected       True
1                     Dataset loaded       True
2                  Columns inspected       True
3            Missing values analyzed       True
4            Duplicate rows analyzed       True
5         Duplicate tickers analyzed       True
6                Data types analyzed       True
7   Descriptive statistics generated       True
8            52-week range inspected       True
9           Excel formulas inspected       True
10            Formula errors checked       True
11       Derived features identified       True
12           Data dictionary created      False